INSERT INTO PRODUCT_INVENTORY(itemId, quantity, location, link) VALUES (1, 35, 'Rome', 'link1')
INSERT INTO PRODUCT_INVENTORY(itemId, quantity, location, link) VALUES (2, 12, 'Milan', 'link2')
INSERT INTO PRODUCT_INVENTORY(itemId, quantity, location, link) VALUES (3, 45, 'Florence', 'link3')
INSERT INTO PRODUCT_INVENTORY(itemId, quantity, location, link) VALUES (4, 87, 'Berlin', 'link4')
INSERT INTO PRODUCT_INVENTORY(itemId, quantity, location, link) VALUES (5, 43, 'Paris', 'link5')
INSERT INTO PRODUCT_INVENTORY(itemId, quantity, location, link) VALUES (6, 32, 'Barcelona', 'link6')
INSERT INTO PRODUCT_INVENTORY(itemId, quantity, location, link) VALUES (7, 53, 'London', 'link7')
